/* SPDX-License-Identifier: GPL-2.0-or-later */

#include "qemu/osdep.h"
#include "dm-mc02-adc-test-common.h"

static void test_adc2_regular_conversion_is_independent(void)
{
    QTestState *qts = qtest_init(
        "-machine dm-mc02,adc-accurate-timing=on");

    qtest_writel(qts, ADC2_SQR1, 0);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_ADRDY);
    g_assert_false(qtest_readl(qts, ADC1_ISR) & ADC_ISR_ADRDY);

    qtest_clock_step(qts, 12000);
    g_assert_true(qtest_readl(qts, ADC2_ISR) &
                  (ADC_ISR_EOC | ADC_ISR_EOS));
    g_assert_cmphex(qtest_readl(qts, ADC2_DR), ==, 0x0100);
    g_assert_false(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);

    qtest_quit(qts);
}

static void test_common_csr_projects_both_adc_status_blocks(void)
{
    QTestState *qts = qtest_init(
        "-machine dm-mc02,adc-accurate-timing=on");
    uint32_t adc1_status;
    uint32_t adc2_status;
    uint32_t expected;
    uint32_t context_a = 1u << ADC_JSQR_JSQ1_SHIFT;
    uint32_t context_b = 2u << ADC_JSQR_JSQ1_SHIFT;
    uint32_t context_c = 3u << ADC_JSQR_JSQ1_SHIFT;

    /* Exercise ready, regular EOC/EOS, and injected JEOC/JEOS on both
     * independent ADC instances, then compare the common projection with
     * their public ISR values. */
    qtest_writel(qts, ADC1_CFGR, ADC_CFGR_JQDIS);
    qtest_writel(qts, ADC2_CFGR, ADC_CFGR_JQDIS);
    qtest_writel(qts, ADC1_SQR1, 0);
    qtest_writel(qts, ADC2_SQR1, 0);
    qtest_writel(qts, ADC1_JSQR, 0);
    qtest_writel(qts, ADC2_JSQR, 0);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART |
                 ADC_CR_JADSTART);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN | ADC_CR_ADSTART |
                 ADC_CR_JADSTART);
    qtest_clock_step(qts, 12000);

    adc1_status = qtest_readl(qts, ADC1_ISR);
    adc2_status = qtest_readl(qts, ADC2_ISR);
    expected = (adc1_status & 0x47f) |
               ((adc2_status & 0x47f) << 16);
    g_assert_cmphex(qtest_readl(qts, ADC12_CSR), ==, expected);
    g_assert_true(expected & ADC_ISR_ADRDY);
    g_assert_true(expected & ADC_ISR_EOC);
    g_assert_true(expected & ADC_ISR_EOS);
    g_assert_true(expected & (ADC_ISR_JEOC << 0));
    g_assert_true(expected & (ADC_ISR_JEOS << 0));
    g_assert_true(expected & (ADC_ISR_ADRDY << 16));

    /* Queue overflow is projected at bit 26 (ADC2 half, when generated by
     * ADC2) just like the other ADC2 ISR bits. */
    qtest_qmp_assert_success(qts, "{ 'execute': 'system_reset' }");
    qtest_writel(qts, ADC2_JSQR, context_a);
    qtest_writel(qts, ADC2_JSQR, context_b);
    qtest_writel(qts, ADC2_JSQR, context_c);
    adc2_status = qtest_readl(qts, ADC2_ISR);
    g_assert_true(adc2_status & ADC_ISR_JQOVF);
    g_assert_true(qtest_readl(qts, ADC12_CSR) & (ADC_ISR_JQOVF << 16));

    /* CSR, CDR and CDR2 are not writable in this boundary slice. */
    expected = qtest_readl(qts, ADC12_CSR);
    qtest_writel(qts, ADC12_CSR, UINT32_MAX);
    qtest_writel(qts, ADC12_CDR, UINT32_MAX);
    qtest_writel(qts, ADC12_CDR2, UINT32_MAX);
    g_assert_cmphex(qtest_readl(qts, ADC12_CSR), ==, expected);
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR), ==, 0);
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR2), ==, 0);

    qtest_quit(qts);
}

static void test_common_cdr_packs_regular_simultaneous_results(void)
{
    QTestState *qts = qtest_init(
        "-machine dm-mc02,adc-accurate-timing=on");

    /* DAMDF=2 is the 32/10-bit multimode transfer format.  ADC2 is the
     * slave: enable it first, then let the ADC1 master start the pair. */
    configure_adc_pll2p(qts);
    qtest_writel(qts, ADC12_CCR, 0x6u | (2u << 14));
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_clock_step(qts, 4500);

    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR), ==, UINT32_C(0x01000100));
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR2), ==, 0);

    /* DAMDF=0 does not pack data.  Reset clears the previous CDR and the
     * bounded producer pairing state. */
    qtest_qmp_assert_success(qts, "{ 'execute': 'system_reset' }");
    qtest_writel(qts, ADC12_CCR, 0x6u);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_clock_step(qts, 1000);
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR), ==, 0);

    qtest_quit(qts);
}

static void test_common_cdr_read_acknowledges_both_eoc(void)
{
    QTestState *qts = qtest_init(
        "-machine dm-mc02,adc-accurate-timing=on");

    configure_adc_pll2p(qts);
    qtest_writel(qts, ADC12_CCR, 0x6u | (2u << 14));
    qtest_writel(qts, ADC1_CFGR, ADC_CFGR_CONT | ADC_CFGR_AUTDLY);
    qtest_writel(qts, ADC2_CFGR, ADC_CFGR_CONT | ADC_CFGR_AUTDLY);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_clock_step(qts, 4500);

    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR), ==,
                    UINT32_C(0x01000100));
    /* Reading the supported common CDR acknowledges both producers and
     * releases the AUTDLY wait state. */
    g_assert_false(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);

    /* The read, rather than a wall-clock delay, is the release event. */
    qtest_clock_step(qts, 4499);
    g_assert_false(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    qtest_clock_step(qts, 1);
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);

    qtest_quit(qts);
}

static void test_common_cdr2_publishes_interleaved_regular_result(void)
{
    QTestState *qts = qtest_init(
        "-machine dm-mc02,adc-accurate-timing=on");
    const uint32_t delay0_ccr = 0x7u;
    const uint32_t delay2_ccr = 0x7u | (2u << 8);

    configure_adc_pll2p(qts);
    /* LL_ADC_MULTI_DUAL_REG_INTERL is DUAL=0x7.  Only the master software
     * start is accepted; the common boundary starts the enabled slave after
     * the master's sampling phase and CCR.DELAY interval. */
    qtest_writel(qts, ADC12_CCR, delay0_ccr);
    qtest_writel(qts, ADC1_CFGR, ADC_CFGR_CONT);
    qtest_writel(qts, ADC2_CFGR, ADC_CFGR_CONT);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    g_assert_cmpint(qtest_clock_step_next(qts), ==, 4500);

    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR2), ==, UINT32_C(0x00000100));
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR), ==, 0);

    /* The fixture's ADC kernel is 4 MHz.  Default sampling is 3/2 cycles and
     * DELAY=0 is another 3/2 cycles, so the slave EOC is 750 ns after the
     * master start plus one 4500 ns rank conversion. */
    g_assert_cmpint(qtest_clock_step_next(qts), ==, 5250);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR2), ==, UINT32_C(0x00000100));

    /* CONT keeps the two kernels in cadence.  Clearing the first pair makes
     * the ordering of the next events visible: M0,S0,M1,S1. */
    qtest_writel(qts, ADC1_ISR, ADC_ISR_EOC | ADC_ISR_EOS);
    qtest_writel(qts, ADC2_ISR, ADC_ISR_EOC | ADC_ISR_EOS);
    g_assert_cmpint(qtest_clock_step_next(qts), ==, 9000);
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);

    qtest_qmp_assert_success(qts, "{ 'execute': 'system_reset' }");
    configure_adc_pll2p(qts);
    /* DELAY=2 is 3.5 ADC clocks.  It moves the slave EOC from 5250 ns to
     * 5750 ns relative to this sequence start. */
    qtest_writel(qts, ADC12_CCR, delay2_ccr);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    g_assert_cmpint(qtest_clock_step_next(qts), ==, 13500);
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmpint(qtest_clock_step_next(qts), ==, 14750);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR2), ==, UINT32_C(0x00000100));

    qtest_qmp_assert_success(qts, "{ 'execute': 'system_reset' }");
    configure_adc_pll2p(qts);
    /* DUAL=0x3 is regular interleaved plus injected simultaneous.  The
     * regular master/slave cadence is shared with DUAL=0x7; injected trigger
     * routing remains an independent ADC group until its own common-data
     * boundary is implemented. */
    qtest_writel(qts, ADC12_CCR, 0x3u);
    qtest_writel(qts, ADC1_CFGR, ADC_CFGR_CONT);
    qtest_writel(qts, ADC2_CFGR, ADC_CFGR_CONT);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    g_assert_cmpint(qtest_clock_step_next(qts), ==, 19250);
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmpint(qtest_clock_step_next(qts), ==, 20000);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR2), ==, UINT32_C(0x00000100));
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR), ==, 0);

    qtest_quit(qts);
}

static void test_common_master_start_drives_slave(void)
{
    QTestState *qts = qtest_init(
        "-machine dm-mc02,adc-accurate-timing=on");

    configure_adc_pll2p(qts);
    qtest_writel(qts, ADC12_CCR, 0x6u | (2u << 14));

    /* HAL_ADCEx_MultiModeStart_DMA enables the slave first and issues only
     * the master regular-start command. */
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    g_assert_true(qtest_readl(qts, ADC2_CR) & ADC_CR_ADSTART);
    qtest_clock_step(qts, 4500);
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR), ==,
                    UINT32_C(0x01000100));

    qtest_qmp_assert_success(qts, "{ 'execute': 'system_reset' }");
    configure_adc_pll2p(qts);
    qtest_writel(qts, ADC12_CCR, 0x6u | (2u << 14));
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    /* The slave cannot own a regular start while DUAL=regular simultaneous. */
    g_assert_false(qtest_readl(qts, ADC2_CR) & ADC_CR_ADSTART);
    qtest_clock_step(qts, 4500);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);

    /* A board reset must preserve the runtime common-to-peer wiring. */
    qtest_qmp_assert_success(qts, "{ 'execute': 'system_reset' }");
    configure_adc_pll2p(qts);
    qtest_writel(qts, ADC12_CCR, 0x6u | (2u << 14));
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    g_assert_true(qtest_readl(qts, ADC2_CR) & ADC_CR_ADSTART);
    qtest_clock_step(qts, 4500);
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);

    qtest_quit(qts);
}

static void test_common_external_trigger_drives_slave(void)
{
    QTestState *qts = qtest_init(
        "-machine dm-mc02,adc-accurate-timing=on");
    uint32_t cfgr = (7u << 5) | (1u << 10);

    configure_adc_pll2p(qts);
    configure_timer_fixture_clock(qts);
    qtest_writel(qts, ADC12_CCR, 0x6u | (2u << 14));
    qtest_writel(qts, ADC1_CFGR, cfgr);
    qtest_writel(qts, ADC2_CFGR, cfgr);
    qtest_writel(qts, ADC1_SQR1, 0);
    qtest_writel(qts, ADC2_SQR1, 0);

    /* External ADSTART only arms each converter.  It must not take the
     * software-start admission path or allocate an unrelated pair ID. */
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    g_assert_true(qtest_readl(qts, ADC1_CR) & ADC_CR_ADSTART);
    g_assert_true(qtest_readl(qts, ADC2_CR) & ADC_CR_ADSTART);

    /* TIM8_TRGO is consumed by the ADC1/master sink first.  The common
     * admission callback starts ADC2 through the shared-ID peer boundary;
     * both ranks then publish one CDR pair. */
    qtest_writel(qts, TIM8_CR2, 2u << 4);
    qtest_writel(qts, TIM8_EGR, 1u);
    qtest_clock_step(qts, 12000);
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR), ==,
                    UINT32_C(0x01000100));

    /* A master-only external arm is rejected at the common boundary rather
     * than producing an unmatched ADC1 result. */
    qtest_qmp_assert_success(qts, "{ 'execute': 'system_reset' }");
    configure_adc_pll2p(qts);
    configure_timer_fixture_clock(qts);
    qtest_writel(qts, ADC12_CCR, 0x6u | (2u << 14));
    qtest_writel(qts, ADC1_CFGR, cfgr);
    qtest_writel(qts, ADC2_CFGR, cfgr);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_writel(qts, TIM8_CR2, 2u << 4);
    qtest_writel(qts, TIM8_EGR, 1u);
    qtest_clock_step(qts, 12000);
    g_assert_cmphex(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC, ==, 0);
    g_assert_cmphex(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC, ==, 0);

    qtest_quit(qts);
}

static void test_common_multimode_dma(bool endpoint)
{
    QTestState *qts;
    uint32_t samples[2] = { 0, 0 };
    uint32_t cr = DMA_CR_EN | DMA_CR_MINC | DMA_CR_TCIE |
                  DMA_CR_PSIZE_32 | DMA_CR_MSIZE_32;
    char machine[96];

    g_snprintf(machine, sizeof(machine),
               "-machine dm-mc02,adc-accurate-timing=on,adc-dma-endpoint=%s",
               endpoint ? "on" : "off");
    qts = qtest_init(machine);
    configure_adc_pll2p(qts);

    /* HAL_ADCEx_MultiModeStart_DMA() programs the common block before it
     * starts the ADC1/master.  Without DUAL/DAMDF this is two independent
     * ADC conversions, so ADC2 never joins the CDR pair and no common DMA
     * request can be produced. */
    qtest_writel(qts, ADC12_CCR, 6u | (2u << 14));

    /* HAL_ADCEx_MultiModeStart_DMA() selects the common CDR, not ADC1->DR.
     * Stream 0 is connected to the board's ADC1 request 9. */
    qtest_writel(qts, DMAMUX1_BASE, 9u);
    qtest_writel(qts, DMA1_S0PAR, ADC12_CDR);
    qtest_writel(qts, DMA1_S0M0AR, 0x20000100);
    qtest_writel(qts, DMA1_S0NDTR, ARRAY_SIZE(samples));
    qtest_memwrite(qts, 0x20000100, samples, sizeof(samples));
    qtest_writel(qts, DMA1_S0CR, cr);
    qtest_writel(qts, ADC1_CFGR, ADC_CFGR_DMA_CIRCULAR);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_clock_step(qts, 9000);

    qtest_memread(qts, 0x20000100, samples, sizeof(samples));
    /* The two legacy ranks form two successive common CDR words. */
    g_assert_cmphex(samples[0], ==, UINT32_C(0x01000100));
    g_assert_cmphex(samples[1], ==, UINT32_C(0x02000200));
    g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 0);
    g_assert_true(qtest_readl(qts, DMA1_LISR) & (1u << 5));
    g_assert_false(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR), ==,
                    UINT32_C(0x02000200));

    qtest_quit(qts);
}

static void test_common_fifo_consuming(gconstpointer opaque)
{
    unsigned flags = GPOINTER_TO_UINT(opaque);
    bool cdr2 = flags & 1;
    bool endpoint = flags & 2;
    bool bad_destination = flags & 4;
    char machine[128];
    QTestState *qts;

    g_snprintf(machine, sizeof(machine),
               "-machine dm-mc02,adc-accurate-timing=on,adc-dma-endpoint=%s",
               endpoint ? "on" : "off");
    qts = qtest_init(machine);
    configure_adc_pll2p(qts);
    qtest_writel(qts, ADC12_CCR, (cdr2 ? 7u : 6u) | (2u << 14));
    qtest_writel(qts, ADC1_SQR1, 0);
    qtest_writel(qts, ADC2_SQR1, 0);
    qtest_writel(qts, DMAMUX1_BASE, 9);
    qtest_writel(qts, DMA1_S0PAR, cdr2 ? ADC12_CDR2 : ADC12_CDR);
    qtest_writel(qts, DMA1_S0M0AR,
                  bad_destination ? 0xdead0000 : 0x20000100);
    qtest_writel(qts, 0x20000100, 0);
    qtest_writel(qts, DMA1_S0NDTR, 1);
    qtest_writel(qts, DMA1_BASE + 0x24, 4); /* DMDIS: FIFO, quarter threshold */
    qtest_writel(qts, DMA1_S0CR,
                  DMA_CR_EN | DMA_CR_PSIZE_32 | DMA_CR_MSIZE_32);
    qtest_writel(qts, ADC1_CFGR, ADC_CFGR_DMA_CIRCULAR);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_clock_step(qts, 4500);
    g_assert_false(qtest_readl(qts, DMA1_S0CR) & DMA_CR_EN);
    /* FIFO reads consume before the memory write, even if it fails. */
    g_assert_false(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    if (bad_destination) {
        g_assert_true(qtest_readl(qts, DMA1_LISR) & (1u << 3));
        g_assert_false(qtest_readl(qts, DMA1_LISR) & (1u << 5));
        g_assert_cmphex(qtest_readl(qts, 0x20000100), ==, 0);
    } else {
        g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 0);
        g_assert_true(qtest_readl(qts, DMA1_LISR) & (1u << 5));
        g_assert_false(qtest_readl(qts, DMA1_LISR) & (1u << 3));
        g_assert_cmphex(qtest_readl(qts, 0x20000100), ==,
                        cdr2 ? 0x100 : 0x01000100);
    }
    qtest_quit(qts);
}

static void test_common_multimode_dma_overrun_request_gate(bool endpoint,
                                                          unsigned retry_mask)
{
    QTestState *qts;
    uint32_t sample = 0;
    uint32_t cr = DMA_CR_EN | DMA_CR_PSIZE_32 | DMA_CR_MSIZE_32;
    char machine[128];

    g_snprintf(machine, sizeof(machine),
               "-machine dm-mc02,adc-accurate-timing=on,"
               "adc-dma-endpoint=%s", endpoint ? "on" : "off");
    qts = qtest_init(machine);
    configure_adc_pll2p(qts);

    qtest_writel(qts, ADC12_CCR, 6u | (2u << 14));

    /* Keep request 9 and the CDR destination configured, but leave the
     * stream disabled for the first two common results.  The first result
     * sets EOC; the second must set OVR and stop common CDR DMA. */
    qtest_writel(qts, DMAMUX1_BASE, 9u);
    qtest_writel(qts, DMA1_S0PAR, ADC12_CDR);
    qtest_writel(qts, DMA1_S0M0AR, 0x20000100);
    qtest_writel(qts, DMA1_S0NDTR, 1u);
    qtest_memwrite(qts, 0x20000100, &sample, sizeof(sample));
    qtest_writel(qts, ADC1_CFGR, ADC_CFGR_DMA_CIRCULAR | ADC_CFGR_CONT);
    qtest_writel(qts, ADC2_CFGR, ADC_CFGR_CONT);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);

    qtest_clock_step(qts, 4500);
    g_assert_cmphex(qtest_readl(qts, ADC1_ISR) &
                    (ADC_ISR_EOC | ADC_ISR_OVR), ==, ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, ADC2_ISR) &
                    (ADC_ISR_EOC | ADC_ISR_OVR), ==, ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 1);

    qtest_clock_step(qts, 4500);
    g_assert_cmphex(qtest_readl(qts, ADC1_ISR) &
                    (ADC_ISR_EOC | ADC_ISR_OVR), ==,
                    ADC_ISR_EOC | ADC_ISR_OVR);
    g_assert_cmphex(qtest_readl(qts, ADC2_ISR) &
                    (ADC_ISR_EOC | ADC_ISR_OVR), ==,
                    ADC_ISR_EOC | ADC_ISR_OVR);
    g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 1);
    g_assert_cmphex(qtest_readl(qts, 0x20000100), ==, 0);

    if (retry_mask) {
        if (!(retry_mask & 1)) {
            qtest_writel(qts, ADC1_ISR, ADC_ISR_OVR);
        }
        if (!(retry_mask & 2)) {
            qtest_writel(qts, ADC2_ISR, ADC_ISR_OVR);
        }
        qtest_writel(qts, DMA1_S0CR, cr);
        g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 1);
        g_assert_cmphex(qtest_readl(qts, DMA1_LISR), ==, 0);
        g_assert_cmphex(qtest_readl(qts, 0x20000100), ==, 0);
        g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
        g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
        /* Retry the same pending word after OVR clears, with no new
         * conversion or virtual-clock step. */
        qtest_writel(qts, DMA1_S0CR, cr & ~DMA_CR_EN);
        qtest_writel(qts, ADC1_ISR, ADC_ISR_OVR);
        qtest_writel(qts, ADC2_ISR, ADC_ISR_OVR);
        qtest_writel(qts, DMA1_S0CR, cr);
        g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 0);
        g_assert_cmphex(qtest_readl(qts, 0x20000100), ==, 0x02000200);
        g_assert_true(qtest_readl(qts, DMA1_LISR) & (1u << 5));
        g_assert_false(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
        g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
        qtest_quit(qts);
        return;
    }

    /* A software CDR read consumes both pending EOC flags but not OVR.  The
     * request gate therefore remains closed until firmware clears both OVR
     * flags explicitly. */
    g_assert_cmphex(qtest_readl(qts, ADC12_CDR), ==,
                    UINT32_C(0x02000200));
    g_assert_cmphex(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC, ==, 0);
    g_assert_cmphex(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC, ==, 0);
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_OVR);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_OVR);
    qtest_writel(qts, ADC1_ISR, ADC_ISR_OVR);
    qtest_writel(qts, ADC2_ISR, ADC_ISR_OVR);
    g_assert_cmphex(qtest_readl(qts, ADC1_ISR) & ADC_ISR_OVR, ==, 0);
    g_assert_cmphex(qtest_readl(qts, ADC2_ISR) & ADC_ISR_OVR, ==, 0);

    qtest_writel(qts, DMA1_S0CR, cr);
    qtest_clock_step(qts, 4500);
    g_assert_cmphex(qtest_readl(qts, 0x20000100), ==,
                    UINT32_C(0x01000100));
    g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 0);
    g_assert_true(qtest_readl(qts, DMA1_LISR) & (1u << 5));
    g_assert_false(qtest_readl(qts, ADC1_ISR) &
                   (ADC_ISR_EOC | ADC_ISR_OVR));
    g_assert_false(qtest_readl(qts, ADC2_ISR) &
                   (ADC_ISR_EOC | ADC_ISR_OVR));

    qtest_quit(qts);
}

static void test_common_multimode_dma_overrun_request_gate_endpoint(void)
{
    test_common_multimode_dma_overrun_request_gate(true, 0);
}

static void test_common_multimode_dma_overrun_request_gate_mmio(void)
{
    test_common_multimode_dma_overrun_request_gate(false, 0);
}

static void test_common_dma_overrun_retry(gconstpointer opaque)
{
    test_common_multimode_dma_overrun_request_gate(true,
                                                  GPOINTER_TO_UINT(opaque));
}

static void test_common_interleaved_external_trigger_cadence(void)
{
    QTestState *qts = qtest_init(
        "-machine dm-mc02,adc-accurate-timing=on");
    uint32_t cfgr = (7u << 5) | (1u << 10);

    configure_adc_pll2p(qts);
    configure_timer_fixture_clock(qts);
    qtest_writel(qts, ADC12_CCR, 0x7u);
    qtest_writel(qts, ADC1_CFGR, cfgr);
    qtest_writel(qts, ADC2_CFGR, cfgr);
    qtest_writel(qts, ADC1_SQR1, 0);
    qtest_writel(qts, ADC2_SQR1, 0);

    /* Both ADCs arm ADSTART, but only the master may consume the regular
     * trigger edge in interleaved mode. */
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_writel(qts, TIM8_CR2, 2u << 4);
    qtest_writel(qts, TIM8_EGR, 1u);

    /* The 4 MHz fixture completes the master at 4500 ns and the default
     * DELAY=0 places the slave at 5250 ns (3/2 sampling + 3/2 delay cycles). */
    g_assert_cmpint(qtest_clock_step_next(qts), ==, 4500);
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmpint(qtest_clock_step_next(qts), ==, 5250);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);

    qtest_quit(qts);
}

static void test_common_interleaved_injected_simultaneous(void)
{
    QTestState *qts = qtest_init(
        "-machine dm-mc02,adc-accurate-timing=on");
    uint32_t jsqr = (9u << ADC_JSQR_JEXTSEL_SHIFT) |
                    ADC_JSQR_JEXTEN_RISING;

    configure_adc_pll2p(qts);
    configure_timer_fixture_clock(qts);
    qtest_writel(qts, ADC12_CCR, 0x3u);
    qtest_writel(qts, ADC1_CFGR, ADC_CFGR_JQDIS);
    qtest_writel(qts, ADC2_CFGR, ADC_CFGR_JQDIS);
    qtest_writel(qts, ADC1_JSQR, jsqr);
    qtest_writel(qts, ADC2_JSQR, jsqr);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_JADSTART);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN | ADC_CR_JADSTART);
    qtest_writel(qts, TIM8_CR2, 2u << 4);
    qtest_writel(qts, TIM8_EGR, 1u);

    /* DUAL=0x3 shares the regular-interleaved mode but keeps injected
     * simultaneous trigger delivery as a separate ADC group.  Both injected
     * kernels receive the same trigger timestamp and complete together. */
    g_assert_cmpint(qtest_clock_step_next(qts), ==, 4500);
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_JEOC);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_JEOC);
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_JEOS);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_JEOS);

    qtest_quit(qts);
}

static void test_common_interleaved_damdf_dma(bool endpoint, unsigned dual,
                                              unsigned damdf)
{
    QTestState *qts;
    uint32_t samples[2] = { 0, 0 };
    uint32_t cr = DMA_CR_EN | DMA_CR_MINC;
    unsigned cdr_address;
    unsigned transfer_count;
    char machine[96];

    if (damdf == 2) {
        cr |= DMA_CR_PSIZE_32 | DMA_CR_MSIZE_32;
        cdr_address = ADC12_CDR2;
        transfer_count = 2;
    } else {
        cr |= DMA_CR_PSIZE_16 | DMA_CR_MSIZE_16;
        cdr_address = ADC12_CDR;
        transfer_count = 1;
    }

    g_snprintf(machine, sizeof(machine),
               "-machine dm-mc02,adc-accurate-timing=on,adc-dma-endpoint=%s",
               endpoint ? "on" : "off");
    qts = qtest_init(machine);
    configure_adc_pll2p(qts);

    /* DAMDF=2 selects alternating 32-bit CDR2 beats. DAMDF=3 instead packs
     * four alternating 8-bit results into CDR and transfers one half-word. */
    qtest_writel(qts, ADC12_CCR, dual | (damdf << 14));
    qtest_writel(qts, ADC1_SQR1, 4u << 6);
    qtest_writel(qts, ADC2_SQR1, 0);
    qtest_writel(qts, DMAMUX1_BASE, 9u);
    qtest_writel(qts, DMA1_S0PAR, cdr_address);
    qtest_writel(qts, DMA1_S0M0AR, 0x20000100);
    qtest_writel(qts, DMA1_S0NDTR, transfer_count);
    qtest_memwrite(qts, 0x20000100, samples, sizeof(samples));
    qtest_writel(qts, DMA1_S0CR, cr);
    qtest_writel(qts, ADC1_CFGR, ADC_CFGR_DMA_CIRCULAR | ADC_CFGR_CONT);
    qtest_writel(qts, ADC2_CFGR, ADC_CFGR_CONT);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);

    /* DAMDF=2 consumes the master CDR2 value immediately. DAMDF=3 merely
     * accumulates the first byte and must not issue a partial DMA request. */
    g_assert_cmpint(qtest_clock_step_next(qts), ==, 4500);
    if (damdf == 2) {
        g_assert_false(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
        g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
        samples[0] = 0;
        qtest_memread(qts, 0x20000100, samples, sizeof(uint32_t));
        g_assert_cmphex(samples[0], ==, qtest_readl(qts, ADC1_DR));
    } else {
        g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
        g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 1);
    }

    /* The delayed slave provides the next alternating byte.  DAMDF=3 now
     * has two bytes only, so the DMA stream remains untouched. */
    g_assert_cmpint(qtest_clock_step_next(qts), ==, 5250);
    if (damdf == 2) {
        g_assert_false(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
        g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
        samples[1] = 0;
        qtest_memread(qts, 0x20000104, &samples[1], sizeof(uint32_t));
        g_assert_cmphex(samples[1], ==, qtest_readl(qts, ADC2_DR));
    } else {
        g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
        g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
        g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 1);
        /* M1 and S1 complete at 9000 and 9750 ns.  The fourth value makes
         * the complete CDR word valid.  ADC1 rank 1 is the board VIN sense
         * channel (24 V through the 11:1 divider -> raw low byte 0x41),
         * while ADC2 rank 1 uses the deterministic 0x0100 fallback; DAMDF=3
         * therefore emits M0,S0,M1,S1 = 0x41,0x00,0x41,0x00. */
        g_assert_cmpint(qtest_clock_step_next(qts), ==, 9000);
        g_assert_cmpint(qtest_clock_step_next(qts), ==, 9750);
        g_assert_false(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
        g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
        g_assert_cmphex(qtest_readl(qts, ADC12_CDR), ==,
                        UINT32_C(0x00410041));
        qtest_memread(qts, 0x20000100, samples, sizeof(uint16_t));
        g_assert_cmphex(samples[0] & 0xffffu, ==, UINT32_C(0x0041));
    }
    g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 0);
    g_assert_true(qtest_readl(qts, DMA1_LISR) & (1u << 5));

    qtest_quit(qts);
}

static void test_common_cdr2_dma_endpoint(void)
{
    test_common_interleaved_damdf_dma(true, 0x7u, 2);
    test_common_interleaved_damdf_dma(true, 0x3u, 2);
}

static void test_common_cdr2_dma_endpoint_reservation(unsigned dual)
{
    QTestState *qts = qtest_init(
        "-machine dm-mc02,adc-accurate-timing=on,adc-dma-endpoint=on");
    uint32_t sample = 0;
    uint32_t cr = DMA_CR_EN | DMA_CR_PSIZE_32 | DMA_CR_MSIZE_32;

    configure_adc_pll2p(qts);
    qtest_writel(qts, ADC12_CCR, dual | (2u << 14));
    qtest_writel(qts, ADC1_SQR1, 0);
    qtest_writel(qts, ADC2_SQR1, 0);
    qtest_writel(qts, DMAMUX1_BASE, 9u);
    qtest_writel(qts, DMA1_S0PAR, ADC12_CDR2);
    qtest_writel(qts, DMA1_S0M0AR, 0x60000000u);
    qtest_writel(qts, DMA1_S0NDTR, 1u);
    qtest_memwrite(qts, 0x20000100, &sample, sizeof(sample));
    qtest_writel(qts, DMA1_S0CR, cr);
    qtest_writel(qts, ADC1_CFGR,
                 ADC_CFGR_DMA_CIRCULAR | ADC_CFGR_AUTDLY);
    qtest_writel(qts, ADC2_CFGR, ADC_CFGR_AUTDLY);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_clock_step(qts, 4500);

    /* The invalid destination must abort CDR2's source reservation.  The
     * first result and its producer EOC remain available for retry. */
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 1);
    g_assert_false(qtest_readl(qts, DMA1_S0CR) & DMA_CR_EN);
    g_assert_true(qtest_readl(qts, DMA1_LISR) & (1u << 3));
    g_assert_cmphex(qtest_readl(qts, 0x20000100), ==, 0);

    /* Re-enabling the matching stream retries the same CDR2 word without a
     * new conversion and commits only ADC1's source-specific EOC. */
    qtest_writel(qts, DMA1_LIFCR, 0x3du);
    qtest_writel(qts, DMA1_S0M0AR, 0x20000100);
    qtest_writel(qts, DMA1_S0NDTR, 1u);
    qtest_writel(qts, DMA1_S0CR, cr);
    g_assert_cmphex(qtest_readl(qts, 0x20000100), ==,
                    UINT32_C(0x00000100));
    g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 0);
    g_assert_true(qtest_readl(qts, DMA1_LISR) & (1u << 5));
    g_assert_false(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);

    qtest_quit(qts);
}

static void test_common_cdr2_dma_endpoint_reservation_retry(void)
{
    test_common_cdr2_dma_endpoint_reservation(0x7u);
    test_common_cdr2_dma_endpoint_reservation(0x3u);
}

static void test_common_cdr2_dma_mmio(void)
{
    test_common_interleaved_damdf_dma(false, 0x7u, 2);
    test_common_interleaved_damdf_dma(false, 0x3u, 2);
}

static void test_common_interleaved_damdf8_dma_endpoint(void)
{
    test_common_interleaved_damdf_dma(true, 0x7u, 3);
    test_common_interleaved_damdf_dma(true, 0x3u, 3);
}

static void test_common_interleaved_damdf8_dma_mmio(void)
{
    test_common_interleaved_damdf_dma(false, 0x7u, 3);
    test_common_interleaved_damdf_dma(false, 0x3u, 3);
}

static void test_common_multimode_dma_endpoint(void)
{
    test_common_multimode_dma(true);
}

static void test_common_multimode_dma_mmio(void)
{
    test_common_multimode_dma(false);
}

static void test_common_multimode_dma_endpoint_reservation_retry(void)
{
    QTestState *qts = qtest_init(
        "-machine dm-mc02,adc-accurate-timing=on,adc-dma-endpoint=on");
    uint32_t sample = 0;
    uint32_t cr = DMA_CR_EN | DMA_CR_PSIZE_32 | DMA_CR_MSIZE_32;

    configure_adc_pll2p(qts);
    qtest_writel(qts, ADC12_CCR, 6u | (2u << 14));
    qtest_writel(qts, DMAMUX1_BASE, 9u);
    qtest_writel(qts, DMA1_S0PAR, ADC12_CDR);
    qtest_writel(qts, DMA1_S0M0AR, 0x60000000u);
    qtest_writel(qts, DMA1_S0NDTR, 1u);
    qtest_memwrite(qts, 0x20000100, &sample, sizeof(sample));
    qtest_writel(qts, DMA1_S0CR, cr);
    qtest_writel(qts, ADC1_CFGR,
                 ADC_CFGR_DMA_CIRCULAR | ADC_CFGR_AUTDLY);
    qtest_writel(qts, ADC2_CFGR, ADC_CFGR_AUTDLY);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_clock_step(qts, 4500);

    /* Invalid P2M memory aborts the common source reservation.  DMA reports
     * TEIF and stops, but CDR's two producer EOC flags remain for retry. */
    g_assert_true(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_true(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);
    g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 1);
    g_assert_false(qtest_readl(qts, DMA1_S0CR) & DMA_CR_EN);
    g_assert_true(qtest_readl(qts, DMA1_LISR) & (1u << 3));
    g_assert_cmphex(qtest_readl(qts, 0x20000100), ==, 0);

    /* Stream enable is the level-like retry boundary.  It moves the same
     * CDR word exactly once and commits the common read acknowledgement. */
    qtest_writel(qts, DMA1_LIFCR, 0x3du);
    qtest_writel(qts, DMA1_S0M0AR, 0x20000100);
    qtest_writel(qts, DMA1_S0NDTR, 1u);
    qtest_writel(qts, DMA1_S0CR, cr);
    g_assert_cmphex(qtest_readl(qts, 0x20000100), ==,
                    UINT32_C(0x01000100));
    g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 0);
    g_assert_true(qtest_readl(qts, DMA1_LISR) & (1u << 5));
    g_assert_false(qtest_readl(qts, ADC1_ISR) & ADC_ISR_EOC);
    g_assert_false(qtest_readl(qts, ADC2_ISR) & ADC_ISR_EOC);

    qtest_quit(qts);
}

static void test_common_multimode_dma_request_cache_key(void)
{
    QTestState *qts = qtest_init(
        "-machine dm-mc02,adc-accurate-timing=on,adc-dma-endpoint=on");
    uint32_t adc_samples[2] = { 0, 0 };
    uint32_t cdr_samples[2] = { 0, 0 };
    uint32_t cr = DMA_CR_EN | DMA_CR_MINC | DMA_CR_PSIZE_32 |
                 DMA_CR_MSIZE_32;

    configure_adc_pll2p(qts);
    qtest_writel(qts, ADC12_CCR, 6u | (2u << 14));

    /* Request 9 is shared by ADC1->DR and ADC12_COMMON->CDR.  Give each
     * endpoint its own stream so a cached negative/positive lookup for one
     * peripheral address cannot select or suppress the other stream. */
    qtest_writel(qts, DMAMUX1_BASE + 0, 9u);
    qtest_writel(qts, DMAMUX1_BASE + 4, 9u);
    qtest_writel(qts, DMA1_S0PAR, ADC1_DR);
    qtest_writel(qts, DMA1_S0M0AR, 0x20000100);
    qtest_writel(qts, DMA1_S0NDTR, ARRAY_SIZE(adc_samples));
    qtest_writel(qts, DMA1_S1PAR, ADC12_CDR);
    qtest_writel(qts, DMA1_S1M0AR, 0x20000200);
    qtest_writel(qts, DMA1_S1NDTR, ARRAY_SIZE(cdr_samples));
    qtest_memwrite(qts, 0x20000100, adc_samples, sizeof(adc_samples));
    qtest_memwrite(qts, 0x20000200, cdr_samples, sizeof(cdr_samples));
    qtest_writel(qts, DMA1_S0CR, cr);
    qtest_writel(qts, DMA1_S1CR, cr);
    qtest_writel(qts, ADC1_CFGR, ADC_CFGR_DMA_CIRCULAR);
    qtest_writel(qts, ADC2_CR, ADC_CR_ADEN);
    qtest_writel(qts, ADC1_CR, ADC_CR_ADEN | ADC_CR_ADSTART);
    qtest_clock_step(qts, 9000);

    qtest_memread(qts, 0x20000100, adc_samples, sizeof(adc_samples));
    qtest_memread(qts, 0x20000200, cdr_samples, sizeof(cdr_samples));
    g_assert_cmphex(adc_samples[0], ==, UINT32_C(0x00000100));
    g_assert_cmphex(adc_samples[1], ==, UINT32_C(0x00000200));
    g_assert_cmphex(cdr_samples[0], ==, UINT32_C(0x01000100));
    g_assert_cmphex(cdr_samples[1], ==, UINT32_C(0x02000200));
    g_assert_cmphex(qtest_readl(qts, DMA1_S0NDTR), ==, 0);
    g_assert_cmphex(qtest_readl(qts, DMA1_S1NDTR), ==, 0);
    g_assert_true(qtest_readl(qts, DMA1_LISR) & (1u << 5));
    g_assert_true(qtest_readl(qts, DMA1_LISR) & (1u << 11));

    qtest_quit(qts);
}

void dm_mc02_adc_register_common_tests(void)
{
    g_test_add_func("/dm-mc02/adc/adc2-regular-conversion-independent",
                    test_adc2_regular_conversion_is_independent);
    g_test_add_func("/dm-mc02/adc/common-csr-status-projection",
                    test_common_csr_projects_both_adc_status_blocks);
    g_test_add_func("/dm-mc02/adc/common-cdr-regular-simultaneous",
                    test_common_cdr_packs_regular_simultaneous_results);
    g_test_add_func("/dm-mc02/adc/common-cdr-read-acknowledges-both-eoc",
                    test_common_cdr_read_acknowledges_both_eoc);
    g_test_add_func("/dm-mc02/adc/common-cdr2-regular-interleaved",
                    test_common_cdr2_publishes_interleaved_regular_result);
    g_test_add_func("/dm-mc02/adc/common-master-start-drives-slave",
                    test_common_master_start_drives_slave);
    g_test_add_func("/dm-mc02/adc/common-external-trigger-drives-slave",
                    test_common_external_trigger_drives_slave);
    g_test_add_func("/dm-mc02/adc/common-interleaved-external-trigger-cadence",
                    test_common_interleaved_external_trigger_cadence);
    g_test_add_func("/dm-mc02/adc/common-interleaved-injected-simultaneous",
                    test_common_interleaved_injected_simultaneous);
    g_test_add_func("/dm-mc02/adc/common-cdr2-dma-endpoint",
                    test_common_cdr2_dma_endpoint);
    g_test_add_func("/dm-mc02/adc/common-cdr2-dma-endpoint-reservation-retry",
                    test_common_cdr2_dma_endpoint_reservation_retry);
    g_test_add_func("/dm-mc02/adc/common-cdr2-dma-mmio",
                    test_common_cdr2_dma_mmio);
    g_test_add_func("/dm-mc02/adc/common-interleaved-damdf8-dma-endpoint",
                    test_common_interleaved_damdf8_dma_endpoint);
    g_test_add_func("/dm-mc02/adc/common-interleaved-damdf8-dma-mmio",
                    test_common_interleaved_damdf8_dma_mmio);
    g_test_add_func("/dm-mc02/adc/common-multimode-dma-endpoint",
                    test_common_multimode_dma_endpoint);
    g_test_add_func("/dm-mc02/adc/common-multimode-dma-mmio",
                    test_common_multimode_dma_mmio);
    g_test_add_func("/dm-mc02/adc/common-multimode-dma-endpoint-reservation-retry",
                    test_common_multimode_dma_endpoint_reservation_retry);
    for (unsigned flags = 0; flags < 8; ++flags) {
        g_autofree char *name = g_strdup_printf(
            "/dm-mc02/adc/fifo-%s-%s-%s", flags & 1 ? "cdr2" : "cdr",
            flags & 2 ? "endpoint" : "mmio",
            flags & 4 ? "write-error" : "success");
        g_test_add_data_func(name, GUINT_TO_POINTER(flags),
                             test_common_fifo_consuming);
    }
    g_test_add_data_func("/dm-mc02/adc/common-dma-retry-master-ovr",
                         GUINT_TO_POINTER(1), test_common_dma_overrun_retry);
    g_test_add_data_func("/dm-mc02/adc/common-dma-retry-slave-ovr",
                         GUINT_TO_POINTER(2), test_common_dma_overrun_retry);
    g_test_add_data_func("/dm-mc02/adc/common-dma-retry-both-ovr",
                         GUINT_TO_POINTER(3), test_common_dma_overrun_retry);
    g_test_add_func("/dm-mc02/adc/common-multimode-dma-overrun-gate-endpoint",
                    test_common_multimode_dma_overrun_request_gate_endpoint);
    g_test_add_func("/dm-mc02/adc/common-multimode-dma-overrun-gate-mmio",
                    test_common_multimode_dma_overrun_request_gate_mmio);
    g_test_add_func("/dm-mc02/adc/common-multimode-dma-request-cache-key",
                    test_common_multimode_dma_request_cache_key);
}
