#!/usr/bin/env bash
set -Eeuo pipefail

script_dir=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
root_dir=$(CDPATH= cd -- "$script_dir/.." && pwd)
source "$script_dir/qemu-build-env.sh"
source_dir="$root_dir/qemu/upstream"
build_dir="$root_dir/build/qemu"
build_type=${QEMU_BUILD_TYPE:-release}
qom_cast_debug=${QEMU_QOM_CAST_DEBUG:-false}
plugins=${QEMU_TCG_PLUGINS:-false}
device_config=dm-mc02

qemu_configure_args=(
    --target-list=arm-softmmu
    --with-devices-arm="$device_config"
    --disable-docs
    --disable-werror
    --disable-capstone
    --disable-slirp
    --disable-sdl
    --disable-gtk
    --enable-fdt=internal
    --enable-download
    --prefix="$root_dir/build/install"
)

case "$plugins" in
    true) qemu_configure_args+=(--enable-plugins) ;;
    false) qemu_configure_args+=(--disable-plugins) ;;
    *)
        printf 'invalid QEMU_TCG_PLUGINS: %s\n' "$plugins" >&2
        exit 2
        ;;
esac

case "$build_type" in
    debug|debugoptimized|release|minsize|plain) ;;
    *)
        printf 'invalid QEMU_BUILD_TYPE: %s\n' "$build_type" >&2
        exit 2
        ;;
esac

if [[ ! -x "$source_dir/configure" ]]; then
    printf '%s\n' "QEMU source is missing: run git submodule update --init qemu/upstream" >&2
    exit 1
fi

qemu_check_prerequisites

file_contains() {
    local file=$1 needle=$2 contents
    contents=$(<"$file")
    [[ "$contents" == *"$needle"* ]]
}

file_has_exact_line() {
    local file=$1 expected=$2 line
    [[ -r "$file" ]] || return 1
    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" == "$expected" ]] && return 0
    done < "$file"
    return 1
}

toolchain_identity=$(qemu_toolchain_identity "${qemu_configure_args[@]}")

configure_qemu() {
    (
        cd "$build_dir"
        "$source_dir/configure" "${qemu_configure_args[@]}"
    )
    "$root_dir/tools/meson" --version > "$build_dir/.dm-meson-version"
    printf '%s\n' "$toolchain_identity" > "$build_dir/.dm-toolchain"
    rm -f "$build_dir/.dm-qemu-plugins"
}

if ! file_contains "$source_dir/hw/arm/meson.build" "dm_mc02.c" || [[ ! -f "$source_dir/hw/arm/dm_mc02.c" ]]; then
    printf '%s\n' 'blocked: wrong QEMU source; restore the pinned qemu/upstream submodule' >&2
    exit 1
fi
mkdir -p "$build_dir"
if [[ ! -f "$build_dir/build.ninja" || ! -f "$build_dir/.dm-toolchain" ||
      "$(<"$build_dir/.dm-toolchain")" != "$toolchain_identity" ||
      "${QEMU_RECONFIGURE:-0}" == 1 ]]; then
    configure_qemu
fi
# A build directory created before the project-specific device profile was
# introduced may still point at the generic ARM config.  Refresh only that
# stale configuration; ordinary source changes remain Ninja's responsibility.
device_cross="$build_dir/config-meson.cross"
if [[ -f "$build_dir/build.ninja" ]] &&
   ! file_has_exact_line "$device_cross" "arm-softmmu = '$device_config'"; then
    configure_qemu
fi
# A build tree generated by the old project Meson cannot be loaded by the
# source-pinned Meson. Re-run QEMU configure once to recreate its metadata.
meson_identity="$build_dir/.dm-meson-version"
if [[ ! -x "$build_dir/pyvenv/bin/meson" || ! -f "$meson_identity" ||
      "$(<"$meson_identity")" != "$("$build_dir/pyvenv/bin/meson" --version)" ]]; then
    configure_qemu
fi
# Existing build directories may have been created by an older version of
# this script with different Meson options.  Reconfigure only when the
# requested options differ or the caller explicitly asks for it; ordinary
# source changes are handled by Ninja's generated dependency graph.
meson_cmdline="$build_dir/meson-private/cmd_line.txt"
needs_reconfigure=0
if [[ ! -f "$meson_cmdline" ]]; then
    needs_reconfigure=1
elif ! file_has_exact_line "$meson_cmdline" "buildtype = $build_type" ||
     ! file_has_exact_line "$meson_cmdline" "qom_cast_debug = $qom_cast_debug" ||
     ! file_has_exact_line "$meson_cmdline" "plugins = $plugins" ||
     ! file_has_exact_line "$meson_cmdline" 'werror = false'; then
    needs_reconfigure=1
fi
if ((needs_reconfigure)); then
    "$root_dir/tools/meson" setup "$build_dir" "$source_dir" --reconfigure \
        -Dbuildtype="$build_type" -Dqom_cast_debug="$qom_cast_debug" \
        -Dplugins="$plugins" -Dwerror=false >/dev/null
fi
"$root_dir/tools/meson" compile -C "$build_dir" qemu-system-arm
printf 'QEMU build ready: %s (buildtype=%s)\n' "$build_dir/qemu-system-arm" "$build_type"
